import type { CustomDesignStatus } from './types';

const ALLOWED_TRANSITIONS: Record<CustomDesignStatus, CustomDesignStatus[]> = {
  DRAFT: ['PAYMENT_PENDING', 'CANCELLED'],
  PAYMENT_PENDING: ['PAYMENT_PROCESSING', 'PAYMENT_PAID', 'SUBMITTED', 'PAYMENT_FAILED', 'CANCELLED'],
  PAYMENT_PROCESSING: ['PAYMENT_PAID', 'SUBMITTED', 'PAYMENT_FAILED', 'PAYMENT_PENDING', 'MANUAL_REVIEW'],
  PAYMENT_FAILED: ['PAYMENT_PENDING', 'CANCELLED'],
  MANUAL_REVIEW: ['SUBMITTED', 'UNDER_REVIEW', 'CANCELLED'],
  PAYMENT_PAID: ['SUBMITTED'],
  SUBMITTED: ['UNDER_REVIEW', 'CANCELLED'],
  UNDER_REVIEW: ['NEEDS_INFORMATION', 'DESIGN_IN_PROGRESS', 'CANCELLED'],
  NEEDS_INFORMATION: ['UNDER_REVIEW', 'DESIGN_IN_PROGRESS', 'CANCELLED'],
  DESIGN_IN_PROGRESS: ['DESIGN_READY', 'CUSTOMER_APPROVAL_REQUIRED', 'NEEDS_INFORMATION', 'CANCELLED'],
  DESIGN_READY: ['CUSTOMER_APPROVAL_REQUIRED', 'DESIGN_IN_PROGRESS', 'CANCELLED'],
  CUSTOMER_APPROVAL_REQUIRED: ['APPROVED', 'DESIGN_IN_PROGRESS', 'CANCELLED'],
  APPROVED: ['FINAL_PAYMENT_PENDING', 'READY_FOR_PRODUCTION', 'IN_PRODUCTION', 'CANCELLED'],
  FINAL_PAYMENT_PENDING: ['READY_FOR_PRODUCTION', 'IN_PRODUCTION', 'CANCELLED'],
  READY_FOR_PRODUCTION: ['IN_PRODUCTION', 'CANCELLED'],
  IN_PRODUCTION: ['FULFILLED', 'CANCELLED'],
  FULFILLED: [],
  CANCELLED: [],
};

export function isValidStatusTransition(from: CustomDesignStatus, to: CustomDesignStatus): boolean {
  if (from === to) return true;
  const allowed = ALLOWED_TRANSITIONS[from];
  return allowed ? allowed.includes(to) : false;
}

export function getAvailableAdminTransitions(current: CustomDesignStatus): CustomDesignStatus[] {
  return ALLOWED_TRANSITIONS[current] || [];
}
